### ISSUE TITLE
How to post data from another task

### ISSUE THREAD

**Issue by vineethvijayan** [jroehl/gsheet.action#395]
Hey, I want to create a set of commands from another task and then pass it to your function so that It will post to my google sheet.

```
- name: Show Response
          # Loop array and print each row
          for i in ${myArray[*]}; do
            echo $i
          done

          echo vin4
          #Google Spread Sheet
      - name: Google Sheet
        id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.1.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId:<SpreadSheetId>
          commands: | # list of commands, specified as a valid JSON string 
            [
              { "command": "appendData", "args": { "data": [[ "Test1", "Test2", "Test3" , "Test4", "Test5", "Test6", "Test7"]], "minCol": 1, "worksheetTitle": "comments" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

```

I want to create a set of instructions from **Show Response** and then pass to **Google Sheet**

Is it possible from your GitHub action?

**Comment by jroehl** [comment]
Even if the response is very late 🙃:

You can use normal GitHub action outputs for this.

```yaml
name: 'Local test with act'
on:
  push

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
      - name: Show Response
        id: response
        run: |
          json_formatted_array='["A1", "A2", "A3"]'
          echo "data_array=${json_formatted_array}" >> ${GITHUB_OUTPUT}
      - name: gsheet.action
        uses: jroehl/gsheet.action@v2.0.1
        with:
          spreadsheetId: ${{ secrets.TEST_SPREADSHEET_ID }}
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "newSheet" }},
              { "command": "updateData", "args": { "data": [${{ steps.response.outputs.data_array }}] }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
```
