### ISSUE TITLE
Support writing results to file

### ISSUE THREAD

**Issue by johnmorrell** [jroehl/gsheet.action#612]
**Is your feature request related to a problem? Please describe.**
Queries that result in a large JSON output can not be passed via an environment variable, this results in an `Argument list too long` error.

**Describe the solution you'd like**
Pass in a file path where the results can be written to.

**Describe alternatives you've considered**
I have not been able to obtain a large JSON response in any other way.

**Additional context**
I believe the maximum size of an environment variable is imposed with GitHub Actions environment.

**Comment by jroehl** [comment]
Added in [v3.0.0](https://github.com/jroehl/gsheet.action/releases/tag/v3.0.0) as the optional `outputFile` input, from @asibs' work in #615.

```yaml
- uses: jroehl/gsheet.action@v3
  with:
    spreadsheetId: ${{ secrets.SPREADSHEET_ID }}
    outputFile: ./results.json
    commands: |
      [{ "command": "getData", "args": { "minCol": 1 } }]
```

The full results JSON goes to that path. When it passes the 1 MB step-output limit the `results` output becomes `{"outputFile": "...", "truncated": true}` and a notice says so, so a large read no longer fails the step. If the file cannot be written the step still succeeds and `results` still carries the payload, since the commands have already run by then.
