### ISSUE TITLE
What format should the private key be in?

### ISSUE THREAD

**Issue by lpoulter1** [jroehl/gsheet.action#75]
I followed this instructions from google to get a credentials.json this works with the node api. I wasn't sure which part of the key and what format to put into my github env value.

I tried setting `GSHEET_PRIVATE_KEY` to `AYKK3TUnvo180FzxAqAbUGts` which is the value of "client_secret":"AYKK3TUnvo180FzxAqAbUGts" in my credentials.json but I get the error

`##[error]error:0909006C:PEM routines:get_name:no start line`
```
workflow file
name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1NpSCP40KtCK8ClPH8WzE__VYZm0v4sd_2-BpZcPSRD4
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
              { "command": "getData", "args": { "range": "'test sheet'!A2:B3" } }
            ] 
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq

```
